# Site settings
title: Georgina Garcia 
description: Un blog de aprendizaje
url: "https://georginagarcia.github.io/blog/"
author:
  name: "Georginia Garcia"
  email: "georgina.garcia01@estudiant.upf.edu"
  url: "http://www.jacoporabolini.com"

# Build settings
baseurl: /blog # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: true
custom_nav_footer: true
reverse: true
